dataset_config:
  visual_genome:
    return_scene_graph: false
    return_objects: false
    return_relationships: false
    return_features_info: false
    return_region_descriptions: true
    no_unk: true

optimizer:
  type: Adamax
  params:
    eps: 1.0e-08
    lr: 0.005 # 0.01
    weight_decay: 0

evaluation:
  metrics:
  - vqa_accuracy

training:
  # clip_norm_mode: all
  # clip_gradients: true
  # lr_ratio: 0.1
  # lr_scheduler: true
  # lr_steps:
  # - 15000
  # - 18000
  # - 20000
  # - 21000
  max_grad_l2_norm: 0.25
  max_updates: 222000
  use_warmup: true
  warmup_factor: 0.2
  warmup_iterations: 3000
  batch_size: 4 # 512
  num_workers: 0 # 7
  task_size_proportional_sampling: true
  early_stop:
    criteria: visual_genome/vqa_accuracy
    minimize: false
